### PR TITLE
feature: live map dark theme logic

### PR DESCRIPTION
**Pull request by Verdone**
### 🛠 Proposed Changes:

Without authentication, Stadia Maps won't allow for use of their maps for a web application deployed to a domain. The workaround is to dynamically style the map with CSS. In the event that a free dark theme map tile is found we can still implement that. Thank you @Niravanaa for noticing this issue.

### 📝 Details:

- Replace dark theme Stadia maptile with dynamic CSS styles

### 🔗 Related Issue(s):

- N/A

### CODE REVIEW

**Comment by Verdone** [comment]
There's a known issue in Leaflet where [the marker images cannot be found in a production environment](https://github.com/Leaflet/Leaflet/issues/4968). It's associated with Leaflet's icon image location and how it is wrongly referenced during bundling (webpack, vite, etc.).  A workaround was done to get the markers to render on the map for production/preview URLs.

This is a screenshot from the branch's preview URL using the workaround:
map markers from branch preview URL

I'm sure that there's a better way to solve this for a vite+svelte environment (which could probably fix the attribution positioning and zoom control icon sizes pictured above in the top-left corner,) but unfortunately that's out of scope for this project.

With the same workaround, this is a screenshot of what the expected output is supposed to look like, from a local dev build:
map markers from local dev build

**Comment by Niravanaa** [comment]
This is an issue known with Vite when importing CSS stylesheets whose paths are not recognized during build-time.

The work-around, at least with Vite, is to make use of a cloud based host to import css files, the prime example being unpkg.com.

More specifically, the same .css file can be found at https://unpkg.com/leaflet@1.7.1/dist/leaflet.css

This PR should be ready to merge, unless @Verdone has something else otherwise.

**Comment by Verdone** [comment]
> This PR should be ready to merge, unless @Verdone has something else otherwise.

Thank you for the CSS import fix. Edit: There's something I want to test with updating the delivery marker on new tracking event data, once that's done I will confirm that it's ready to merge by tomorrow evening.

**Comment by Verdone** [comment]
Fixed the bug with the delivery marker not being placed properly depending on tracking status, the PR is ready to merge now.

**Review by briantkatch — APPROVED** [review]

**Pull request merged**
